apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team4-argocd
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/KalyanPatnala/argocd11.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: team4

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
