---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: team4-web1
  name: frontend-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: team4-web1
  type: NodePort
